### ISSUE TITLE
On-boarding checklist for Jared O'Neal

### ISSUE THREAD

**Issue by bernhold** [bernhold/atpesc-issues#3]
- [ ] Establish a GitHub account
- [ ] Ask David for access to the project repo
- [ ] Read Team Policy document
- [ ] Propose an addition to the on-boarding checklist for new team members
